### ISSUE TITLE
soundkeeper exits sometimes

### ISSUE THREAD

**Issue by ran-haim** [vrubleg/soundkeeper#3] opened 2022-09-30 11:28 UTC
It seems that sometimes, usually after one day (probably because I close the tv and av) the soundkeeper.exe exists.
I wanted to look in the logs, but it seems you only write to stdoutput so I cannot access that.
Can you add ability to write to a log file?

thanks.

**Comment by vrubleg** [comment] 2022-12-17 13:18
Oh, sorry, I didn't monitor the issues page. Most of communication related to this project happens on the project home page.

I updated the [debug version](https://veg.by/files/winsoft/soundkeeper_debug.7z) that allows to redirect stdout into a file now. Run it like this from `cmd`:

```
soundkeeper.exe > soundkeeper.log
```

But it is suspicious that it exits itself. Maybe it crashes somehow? Please check in the Event Viewer > Windows Logs > Application, look for events with Event Type ID = 1000. If there is something related to the Sound Keeper, it would be really helpful to understand where exactly it crashes. Also, the system should create a crash dump in this case, [check here](https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps) how to collect it.

**Comment by vrubleg** [comment] 2023-01-30 21:24
@ran-haim Maybe it was actually freezing and not terminating itself? A potential bug that could cause a deadlock was fixed in the latest v1.3.1. Please check if it helps you.

**Comment by vrubleg** [comment] 2023-02-04 13:32
Most probably it was actually stopping to work because of the deadlock, but the process was still running. So I guess that the issue is fixed in the latest v1.3.1, so I close this ticket.

**Closed by vrubleg** 2023-02-04 13:32 UTC
